<?php echo $this->render('header.phtml');?>




	<body class="<?=$this->pageClass;?>">
	<div id="divLightboxContent" style="position:absolute; width:650px; z-index: 2000; height: 550px; background:#FFF; top: 50%; left: 50%; display: none;  margin-top: -250px; margin-left: -325px;">

				<!-- DIV LIGHTBOX Categorias de Modalidades -->


	</div>

		<div id="divLightbox" onClick="closeLightbox();" style="position:absolute; z-index: 999; width:100%; height: 100%; background:#000; display: none; opacity: 0.5;"  >



		</div>

		<?php echo $this->render('topo.phtml');?>
		<div id="nav" class="clearfix">

			<?php echo $this->render('menu.phtml');?>
		    <div class="content">
		    	<?php echo $this->layout()->content;?>
		    </div>
	    </div>
	    <div id="footer" style="height: 100px;">

	    </div>



	</body>
</html>