<div id="loader" style="display:none;"></div>

<div style="display:none;" id="myDiv" class="animate-bottom"> </div>
<section id="conteudo">
   
</section>

<script src="/js/usuarios.js" type="text/javascript"></script>
<script type="text/javascript">
     $(document).ready(function(){
         conteudo('<?=$this->url(array('controller' => 'usuario', 'action' => "index"));?>');   
        
    });
    

</script>